
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './component/navbar'
import Footer from "./component/footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "Next-App E-commerce",
    template: "%s | Next-App E-commerce",
  },
  keywords: ["Next-App Commerce" , "react " , "products"],
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className +  "scroll-smooth"}>
      <Navbar />

        {children}
        
        <Footer />
        </body>
    </html>
  );
}
